# Generated by Django 5.0.6 on 2024-06-16 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
